{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf130
{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red44\green50\blue53;\red255\green255\blue255;
\red19\green36\blue126;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl630\partightenfactor0

\f0\fs22 \cf2 \cb1 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec3 web:\
  image: app/client\
  ports:\
    - "80:80"\
app:\
  image: app/service\
  links:\
    - db\
  ports:\
    - "3000:3000"\
  \
db:\
  image: app/mysql\
  ports:\
	-
\f1\fs24 \cb4 \strokec5 "3306:3306"
\f0\fs22 \cb1 \strokec3 \
  environment:\
    MYSQL_USER: root\
    MYSQL_PASSWORD: ashwin92\
    MYSQL_DATABASE:inventory\kerning1\expnd0\expndtw0 \
\pard\pardeftab720\sl377\partightenfactor0

\fs26 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \
}