webapp:
  image: app/client
  ports:
    - "80:80"
    
app:
  image: app/service
  links:
    - db
    - webapp
  ports:
    - "8082:82"
  
db:
  image: app/mysql
  ports:
     -"3306:3306"
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: ashwin92
    MYSQL_DATABASE:inventory

}
